---
functional:
  - У пользователя есть возможность регистрации на сайте, указав личные данные (логин, пароль, мейл), либо используя имеющийся аккаунт GitHub/Discord
  - У пользователя есть возможность авторизоваться в системе, используя личные данные, либо указав имеющийся аккаунт GitHub/Discord
  - Пользователь может создавать или присоединятся к соревнованиям с другими игроками или ботом
  - В системе отображается рейтинг, колличество очков и места участников
  - У пользователя есть возможность простмотра собственной статистики
  - В системе есть возможность чатового общения с другими пользователями во время игры
  - У пользователя есть возможность выбора языка программирования в процессе игры
  - У пользователя есть возможность самостоятельного выбора опции для новой игры
  - Система синхронизирует код в реальном времени
  - У пользователя есть возможность просматривать участников, находящихся "онлайн"
  - После прохождения игры у пользователя есть возможность вернуть в основное меню игры или взять реванш
non-functional:
  - Интерфейс должен быть адаптирован под различные разрешения экрана
  - Сайт должен быть оптимизирован для скорости интернета 
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей)
implicit:
  - Интерфейс должен быть понятен пользователю
  - Прогресс должен сохраняться при различных сбоях
  - Должны всплывать окна с сообщением об ошибке и методах восстановления, в случае ошибки
  - Должна присутствовать локализация на язык носителя и английский язык
  - Дизайн страницы не должен мешать просмотру основного контента и интерфейса
